<template>
  <div class="space-y-6">
    <div>
      <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
        {{ $t('settings.invoicing.title') }}
      </h3>
      <p class="text-sm text-gray-500 dark:text-slate-400">
        {{ $t('settings.invoicing.description') }}
      </p>
    </div>

    <!-- Invoice Numbering -->
    <div class="bg-gray-50 dark:bg-slate-700/50 rounded-lg p-4">
      <h4 class="font-medium text-gray-900 dark:text-white mb-4">
        {{ $t('settings.invoicing.invoiceNumbering') }}
      </h4>
      <div class="space-y-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="font-medium text-gray-900 dark:text-white">
              {{ $t('settings.invoicing.autoGenerate') }}
            </p>
            <p class="text-sm text-gray-500 dark:text-slate-400">
              {{ $t('settings.invoicing.autoGenerateDesc') }}
            </p>
          </div>
          <label class="relative inline-flex items-center cursor-pointer">
            <input
              v-model="localSettings.autoGenerateInvoice"
              type="checkbox"
              class="sr-only peer"
              @change="emitChange"
            />
            <div
              class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-indigo-300 dark:peer-focus:ring-indigo-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-indigo-600"
            ></div>
          </label>
        </div>

        <div class="grid md:grid-cols-3 gap-4 pt-4 border-t border-gray-200 dark:border-slate-600">
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              {{ $t('settings.invoicing.invoicePrefix') }}
            </label>
            <input
              v-model="localSettings.invoicePrefix"
              type="text"
              placeholder="INV"
              class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
              @input="emitChange"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
              {{ $t('settings.invoicing.lastInvoiceNo') }}
            </label>
            <input
              v-model.number="localSettings.lastInvoiceNumber"
              type="number"
              min="0"
              class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
              @input="emitChange"
            />
          </div>
          <div class="flex items-end">
            <label class="flex items-center gap-2 cursor-pointer">
              <input
                v-model="localSettings.invoiceYearSuffix"
                type="checkbox"
                class="w-4 h-4 text-indigo-600 border-gray-300 rounded focus:ring-indigo-500"
                @change="emitChange"
              />
              <span class="text-sm text-gray-700 dark:text-gray-300">{{
                $t('settings.invoicing.addYearSuffix')
              }}</span>
            </label>
          </div>
        </div>

        <div
          class="bg-white dark:bg-slate-800 rounded p-3 border border-gray-200 dark:border-slate-600"
        >
          <p class="text-xs text-gray-500 dark:text-slate-400 mb-1">
            {{ $t('settings.invoicing.exampleInvoiceNo') }}:
          </p>
          <p class="font-mono text-gray-900 dark:text-white">{{ previewInvoiceNumber }}</p>
        </div>
      </div>
    </div>

    <!-- Company Info -->
    <div class="bg-gray-50 dark:bg-slate-700/50 rounded-lg p-4">
      <h4 class="font-medium text-gray-900 dark:text-white mb-4">
        {{ $t('settings.invoicing.companyInfo') }}
      </h4>
      <div class="grid md:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ $t('settings.invoicing.companyName') }}
          </label>
          <input
            v-model="localSettings.companyInfo.name"
            type="text"
            class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            @input="emitChange"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ $t('settings.invoicing.taxOffice') }}
          </label>
          <input
            v-model="localSettings.companyInfo.taxOffice"
            type="text"
            class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            @input="emitChange"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ $t('settings.invoicing.taxNumber') }}
          </label>
          <input
            v-model="localSettings.companyInfo.taxNumber"
            type="text"
            class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            @input="emitChange"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ $t('settings.invoicing.phone') }}
          </label>
          <input
            v-model="localSettings.companyInfo.phone"
            type="text"
            class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            @input="emitChange"
          />
        </div>
        <div>
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ $t('settings.invoicing.email') }}
          </label>
          <input
            v-model="localSettings.companyInfo.email"
            type="email"
            class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            @input="emitChange"
          />
        </div>
        <div class="md:col-span-2">
          <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            {{ $t('settings.invoicing.address') }}
          </label>
          <textarea
            v-model="localSettings.companyInfo.address"
            rows="2"
            class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
            @input="emitChange"
          ></textarea>
        </div>
      </div>
    </div>

    <!-- Invoice Notes -->
    <div class="bg-gray-50 dark:bg-slate-700/50 rounded-lg p-4">
      <h4 class="font-medium text-gray-900 dark:text-white mb-4">
        {{ $t('settings.invoicing.invoiceFooterNote') }}
      </h4>
      <textarea
        v-model="localSettings.invoiceNotes"
        rows="3"
        :placeholder="$t('settings.invoicing.invoiceFooterNotePlaceholder')"
        class="w-full px-3 py-2 border border-gray-300 dark:border-slate-600 rounded-lg bg-white dark:bg-slate-700 text-gray-900 dark:text-white"
        @input="emitChange"
      ></textarea>
    </div>
  </div>
</template>

<script setup>
import { ref, watch, computed } from 'vue'

const props = defineProps({
  modelValue: {
    type: Object,
    default: () => ({})
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const localSettings = ref({
  autoGenerateInvoice: true,
  invoicePrefix: 'INV',
  invoiceYearSuffix: true,
  lastInvoiceNumber: 0,
  companyInfo: {
    name: '',
    taxOffice: '',
    taxNumber: '',
    address: '',
    phone: '',
    email: ''
  },
  invoiceNotes: '',
  ...props.modelValue
})

// Ensure companyInfo is always an object
if (!localSettings.value.companyInfo) {
  localSettings.value.companyInfo = {
    name: '',
    taxOffice: '',
    taxNumber: '',
    address: '',
    phone: '',
    email: ''
  }
}

watch(
  () => props.modelValue,
  newVal => {
    localSettings.value = {
      ...localSettings.value,
      ...newVal,
      companyInfo: { ...localSettings.value.companyInfo, ...(newVal?.companyInfo || {}) }
    }
  },
  { deep: true }
)

const emitChange = () => {
  emit('update:modelValue', localSettings.value)
  emit('change')
}

const previewInvoiceNumber = computed(() => {
  const prefix = localSettings.value.invoicePrefix || 'INV'
  const number = String((localSettings.value.lastInvoiceNumber || 0) + 1).padStart(6, '0')
  const year = new Date().getFullYear()

  if (localSettings.value.invoiceYearSuffix) {
    return `${prefix}-${year}-${number}`
  }
  return `${prefix}-${number}`
})
</script>
